title: Mapping the Immune Response across Time and Severities in COVID-19 patients
description: A template website for ADA
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Introduction
    url: "#introduction"
  - title: Differential Analysis
    url: "#diff_ana"
  - title: Predictive Model
    url: "#pred_mod"
  - title: Gallery
    url: /gallery
  - title: Data
    url: /data