title: Mapping the Immune Response across Time and Severities in COVID-19 Patients
description: A template website for ADA
show_downloads: True
navigation:
  - title: Introduction
    url: "#introduction"
    sublinks:
      - title: Research questions
        url: "#research_questions"
      - title: Data Exploration
        url: "#data_exploration"
  - title: Differential Analysis
    url: "#diff_ana"
    sublinks:
      - title: Single Marker Analysis
        url: "#single_marker_analysis"
      - title: Linear Regression
        url: "#linear_regression"
  - title: Temporal Analysis
    url: "#temp_ana"
  - title: Predictive Model
    url: "#pred_mod"
    sublinks:
      - title: Model Performance
        url: "#model_performance"
      - title: Feature Importance
        url: "#feature_importance"
  - title: Conclusion
    url: "#conclusion"