title: Mapping the Immune Response across Time and Severities in COVID-19 patients
description: A template website for ADA
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: About
    url: about.html